### ISSUE TITLE
Add custom path variable

### ISSUE THREAD

**Issue by groteworld** [manelferreira/serverless-sequelize-migrations#2]
Small feature request here. Could you add the code for a custom field for `path` in the `serverless.yml` file.

It would look like:

```YAML
custom:
  migrationsPath: path/to/your/migrations
```

I've never worked on a serverless plugin so I'm not sure the right way to fully do this, but it looks pretty straight-forward, based off of [serverless-stage-manager](https://github.com/jeremydaly/serverless-stage-manager/blob/master/index.js#L16).

**Comment by manelferreira** [comment]
Hi Blake. That's a nice feature, indeed. I'll take a look this weekend.

I'll let you know as soon as I have something ready.

Thank you very much.

**Comment by manelferreira** [comment]
Hi Blake. 

Sorry for the long delay of the update, I only had the time to make the changes today.
I've just published a new version of the plugin with the requested feature on npm.

Give it a try, please. If you have any problems, let me know so that I can take a look.

Thank you!

**Comment by groteworld** [comment]
Works great! Thank you for your library and time!
