### ISSUE TITLE
Deprecation Warning on serverless 2.39.1

### ISSUE THREAD

**Issue by ricardoul** [manelferreira/serverless-sequelize-migrations#27]
Hello When updating my app to use serverless 2.39.1 I got this deprecation warning
Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - SequelizeMigrations for "path", "verbose", "name", "rollback", "dbDialect", "dbHost", "dbPort", "dbName", "dbUsername", "dbPassword", "times", "status"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA

**Comment by manelferreira** [comment]
I've just released a new update fixing all the stuff that was deprecated. This issue is now solved. Thank you, guys!
