### ISSUE TITLE
Deprecation Warning on serverless 3.28.1

### ISSUE THREAD

**Issue by yavir-me** [manelferreira/serverless-sequelize-migrations#41]
Making different operations with `sls`, receive warning of the deprecation with advice to run `sls doctor`. Running this command, receive the following message:
```
CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
 - SequelizeMigrations for "path", "verbose", "name", "rollback", "dbDialect", "dbHost", "dbPort", "dbName", "dbUsername", "dbPassword", "times", "status"
 ```
 
 I saw that the issue was fixed in PR #34, but the issue still has a place.

**Comment by manelferreira** [comment]
I've just released a new update fixing all the deprecated stuff. This issue is now resolved. Thank you!
